server:
  port: 8081

spring:
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 5000ms
      database: 0
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
          time-between-eviction-runs: 60s

lgh:
  sms:
    ccp:
      serverIp: app.cloopen.com
      port: 8883
      accountSId: 2c94811c9860a9c4019983be47653215
      accountToken: 8589bca661a14e7cadf30dae6b52c08f
      appId: 2c94811c9860a9c4019983be4903321c
      templateId: 1

